<template>
  <Teleport to="body">
    <div v-if="isOpen" class="invoice-overlay" @click.self="closeModal">
      <div class="invoice-modal">
        <!-- Close Button -->
        <button @click="closeModal" class="invoice-close" title="Close">
          <LucideX class="w-4 h-4" />
        </button>

        <!-- Scrollable content area -->
        <div class="invoice-scroll">
        <!-- Printable Invoice Area -->
        <div id="invoice-print-area" class="invoice-body">
          <!-- Header: Logo + INVOICE -->
          <div class="invoice-header">
            <img src="/logo-full.png" alt="Tentaklik" class="invoice-logo" />
            <div class="invoice-header-right">
              <h1 class="invoice-title">INVOICE</h1>
              <span 
                :class="isPaid ? 'bg-emerald-100 text-emerald-700 border-emerald-300' : 'bg-orange-100 text-orange-700 border-orange-300'"
                class="px-2.5 py-0.5 text-xs font-extrabold uppercase rounded-md border inline-block mt-1"
              >
                {{ isPaid ? '✓ PAID' : 'UNPAID / PENDING' }}
              </span>
            </div>
          </div>

          <!-- Meta Info Row -->
          <div class="invoice-meta">
            <div class="invoice-meta-item">
              <span class="invoice-meta-label">Invoice No.</span>
              <span class="invoice-meta-value">{{ transaction?.payment_data?.merchantOrderId || transaction?.id?.substring(0,8) || '-' }}</span>
            </div>
            <div class="invoice-meta-item">
              <span class="invoice-meta-label">Date</span>
              <span class="invoice-meta-value">{{ formatDate(transaction?.created_at) }}</span>
            </div>
            <div class="invoice-meta-item">
              <span class="invoice-meta-label">Payment Method</span>
              <span class="invoice-meta-value">{{ transaction?.payment_data?.paymentName || transaction?.payment_data?.method || 'Transfer' }}</span>
            </div>
          </div>

          <hr class="invoice-divider" />

          <!-- Table-like Item List -->
          <table class="invoice-table">
            <thead>
              <tr>
                <th class="text-left">Item Description</th>
                <th class="text-right">Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{{ transaction?.description || 'Digital Ad Management Service' }}</td>
                <td class="text-right">{{ formatMoney(transaction?.amount) }}</td>
              </tr>
              <tr v-if="Number(transaction?.fee_amount) > 0">
                <td>Service Fee</td>
                <td class="text-right">{{ formatMoney(transaction?.fee_amount) }}</td>
              </tr>
            </tbody>
            <tfoot>
              <tr class="invoice-total-row">
                <td>Total Payable</td>
                <td class="text-right">{{ formatMoney(Number(transaction?.amount || 0) + Number(transaction?.fee_amount || 0)) }}</td>
              </tr>
            </tfoot>
          </table>

          <!-- Footer -->
          <div class="invoice-footer">
            <p>This document is an official payment invoice generated by Tentaklik.</p>
            <p>© {{ new Date().getFullYear() }} Tentaklik — tentaklik.com</p>
          </div>
        </div>
        </div> <!-- /invoice-scroll -->

        <!-- Action Buttons (sticky at bottom) -->
        <div class="invoice-actions">
          <button @click="downloadPdf" class="invoice-btn invoice-btn--outline">
            <LucideDownload class="w-4 h-4" />
            Download PDF
          </button>
          <button @click="shareInvoice" :disabled="isSharing" class="invoice-btn invoice-btn--primary" :style="isSharing ? 'opacity:0.7;cursor:wait' : ''">
            <svg v-if="isSharing" class="w-4 h-4 animate-spin" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="3" opacity="0.3"/><path d="M12 2a10 10 0 0 1 10 10" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>
            <LucideShare2 v-else class="w-4 h-4" />
            {{ isSharing ? 'Processing...' : 'Share' }}
          </button>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { LucideX, LucideDownload, LucideShare2 } from 'lucide-vue-next'
import { useToast } from '#imports'

const props = defineProps({
  isOpen: Boolean,
  transaction: {
    type: Object as () => any,
    required: false,
    default: null,
  },
})

const emit = defineEmits(['close'])
const toast = useToast()

const closeModal = () => emit('close')

const isPaid = computed(() => {
  const status = String(props.transaction?.status || props.transaction?.payment_status || '').toLowerCase()
  return ['success', 'finished', 'confirmed', 'paid', 'lunas'].includes(status)
})

const formatMoney = (amount: number | string | undefined) => {
  if (amount === undefined || amount === null) return '0.00 USDT'
  const isUsd = props.transaction?.currency === 'USD' || 
                props.transaction?.payment_data?.method?.includes('USDT') || 
                props.transaction?.payment_data?.method?.includes('TRC') ||
                props.transaction?.payment_data?.paymentName?.includes('USDT')
  if (isUsd) {
    return `${Number(amount).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} USDT`
  }
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(Number(amount))
}

const formatDate = (dateString: string | undefined) => {
  if (!dateString) return '-'
  return new Intl.DateTimeFormat('en-US', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit'
  }).format(new Date(dateString))
}

const downloadPdf = () => {
  const t = props.transaction
  const orderId = t?.payment_data?.merchantOrderId || t?.id?.substring(0,8) || '-'
  const total = formatMoney(Number(t?.amount || 0) + Number(t?.fee_amount || 0))
  const feeRow = Number(t?.fee_amount) > 0
    ? `<tr><td style="padding:10px 0;color:#374151;border-bottom:1px solid #f3f4f6">Service Fee</td><td style="padding:10px 0;color:#374151;border-bottom:1px solid #f3f4f6;text-align:right">${formatMoney(t?.fee_amount)}</td></tr>`
    : ''

  const statusBadge = isPaid.value 
    ? `<span class="badge" style="background:#dcfce7;color:#15803d">✓ PAID</span>`
    : `<span class="badge" style="background:#ffedd5;color:#c2410c">UNPAID / PENDING</span>`

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Invoice ${orderId}</title>
<style>
  @page { margin: 1.5cm; }
  body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; color: #111827; margin: 0; padding: 2rem; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 1.5rem; }
  .logo { height: 32px; }
  .title { font-size: 2rem; font-weight: 900; letter-spacing: 0.08em; margin: 0; }
  .badge { display: inline-block; padding: 3px 10px; font-size: 0.75rem; font-weight: 700; border-radius: 99px; margin-top: 4px; }
  .meta { margin-bottom: 1.5rem; }
  .meta-row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 0.875rem; }
  .meta-label { color: #6b7280; }
  .meta-value { font-weight: 600; }
  hr { border: none; border-top: 1px solid #e5e7eb; margin: 0 0 1rem; }
  table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
  th { text-align: left; padding: 8px 0; font-weight: 700; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.04em; border-bottom: 2px solid #111827; color: #374151; }
  th:last-child { text-align: right; }
  td { padding: 10px 0; color: #374151; border-bottom: 1px solid #f3f4f6; }
  .total td { padding-top: 12px; font-weight: 800; font-size: 1.1rem; color: #111827; border-top: 2px solid #111827; border-bottom: none; }
  .footer { margin-top: 2rem; text-align: center; font-size: 0.75rem; color: #9ca3af; }
</style>
</head><body>
<div class="header">
  <img src="${window.location.origin}/logo-full.png" class="logo" alt="Tentaklik" />
  <div style="text-align:right">
    <p class="title">INVOICE</p>
    ${statusBadge}
  </div>
</div>
<div class="meta">
  <div class="meta-row"><span class="meta-label">Invoice No.</span><span class="meta-value">${orderId}</span></div>
  <div class="meta-row"><span class="meta-label">Date</span><span class="meta-value">${formatDate(t?.created_at)}</span></div>
  <div class="meta-row"><span class="meta-label">Payment Method</span><span class="meta-value">${t?.payment_data?.paymentName || t?.payment_data?.method || 'Transfer'}</span></div>
</div>
<hr />
<table>
  <thead><tr><th>Item Description</th><th>Amount</th></tr></thead>
  <tbody>
    <tr><td style="padding:10px 0;color:#374151;border-bottom:1px solid #f3f4f6">${t?.description || 'Digital Ad Management Service'}</td><td style="padding:10px 0;color:#374151;border-bottom:1px solid #f3f4f6;text-align:right">${formatMoney(t?.amount)}</td></tr>
    ${feeRow}
  </tbody>
  <tfoot><tr class="total"><td>Total Payable</td><td style="text-align:right">${total}</td></tr></tfoot>
</table>
<div class="footer">
  <p>This document is an official payment invoice generated by Tentaklik.</p>
  <p>© ${new Date().getFullYear()} Tentaklik — tentaklik.com</p>
</div>
</body></html>`

  const printWindow = window.open('', '_blank', 'width=800,height=600')
  if (printWindow) {
    printWindow.document.write(html)
    printWindow.document.close()
    printWindow.onload = () => {
      printWindow.focus()
      printWindow.print()
      printWindow.onafterprint = () => printWindow.close()
      setTimeout(() => {
        try { if (!printWindow.closed) printWindow.close() } catch {}
      }, 1000)
    }
  }
}

const isSharing = ref(false)

const shareInvoice = async () => {
  if (!props.transaction) return
  isSharing.value = true

  try {
    const { toPng } = await import('html-to-image')
    const invoiceEl = document.getElementById('invoice-print-area')
    if (!invoiceEl) throw new Error('Invoice element not found')

    const dataUrl = await toPng(invoiceEl, {
      backgroundColor: '#ffffff',
      pixelRatio: 2,
      quality: 0.95
    })

    const res = await fetch(dataUrl)
    const blob = await res.blob()
    const file = new File([blob], `Invoice-${props.transaction?.payment_data?.merchantOrderId || 'Tentaklik'}.png`, { type: 'image/png' })

    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share({
        title: `Invoice Tentaklik`,
        text: `Invoice Pembayaran Tentaklik #${props.transaction?.payment_data?.merchantOrderId}`,
        files: [file]
      })
      toast.addToast('Invoice shared successfully', 'success')
    } else {
      const link = document.createElement('a')
      link.download = `Invoice-${props.transaction?.payment_data?.merchantOrderId || 'Tentaklik'}.png`
      link.href = dataUrl
      link.click()
      toast.addToast('Invoice saved as PNG', 'success')
    }
  } catch (err: any) {
    console.error('Share invoice failed:', err)
    toast.addToast('Failed to share invoice', 'error')
  } finally {
    isSharing.value = false
  }
}
</script>

<style scoped>
.invoice-overlay {
  position: fixed;
  inset: 0;
  z-index: 9999;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1rem;
  background: rgba(15, 23, 42, 0.65);
  backdrop-filter: blur(8px);
  animation: fadeIn 0.2s ease-out;
}
@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}

.invoice-modal {
  position: relative;
  width: 100%;
  max-width: 520px;
  max-height: 90vh;
  display: flex;
  flex-direction: column;
  background: #ffffff;
  border-radius: 1.5rem;
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
  overflow: hidden;
  animation: modalSlide 0.25s cubic-bezier(0.16, 1, 0.3, 1);
}
@keyframes modalSlide {
  from { opacity: 0; transform: translateY(12px) scale(0.97); }
  to { opacity: 1; transform: translateY(0) scale(1); }
}

.invoice-close {
  position: absolute;
  top: 1.25rem;
  right: 1.25rem;
  z-index: 10;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background: #f1f5f9;
  color: #64748b;
  border: none;
  cursor: pointer;
  transition: all 0.2s;
}
.invoice-close:hover {
  background: #e2e8f0;
  color: #0f172a;
}

.invoice-scroll {
  flex: 1;
  overflow-y: auto;
  padding: 2rem 2rem 1rem 2rem;
}

.invoice-body {
  background: #ffffff;
}

.invoice-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  margin-bottom: 1.5rem;
}
.invoice-logo {
  height: 36px;
  object-fit: contain;
}
.invoice-header-right {
  text-align: right;
}
.invoice-title {
  font-size: 1.75rem;
  font-weight: 900;
  letter-spacing: 0.05em;
  color: #0f172a;
  margin: 0;
  line-height: 1;
}

.invoice-meta {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1rem;
  padding: 1rem;
  background: #f8fafc;
  border-radius: 0.75rem;
  border: 1px solid #f1f5f9;
  margin-bottom: 1.25rem;
}
.invoice-meta-item {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}
.invoice-meta-label {
  font-size: 0.7rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #94a3b8;
}
.invoice-meta-value {
  font-size: 0.8rem;
  font-weight: 700;
  color: #1e293b;
  word-break: break-all;
}

.invoice-divider {
  border: none;
  border-top: 1px dashed #e2e8f0;
  margin: 0 0 1.25rem 0;
}

.invoice-table {
  width: 100%;
  border-collapse: collapse;
  margin-bottom: 1.5rem;
}
.invoice-table th {
  padding: 0.5rem 0;
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #64748b;
  border-bottom: 2px solid #0f172a;
}
.invoice-table td {
  padding: 0.875rem 0;
  font-size: 0.875rem;
  color: #334155;
  border-bottom: 1px solid #f1f5f9;
}
.invoice-total-row td {
  padding-top: 1rem;
  font-size: 1rem;
  font-weight: 800;
  color: #0f172a;
  border-top: 2px solid #0f172a;
  border-bottom: none;
}

.invoice-footer {
  text-align: center;
  font-size: 0.75rem;
  color: #94a3b8;
  padding-top: 1rem;
  border-top: 1px solid #f1f5f9;
}
.invoice-footer p {
  margin: 0.125rem 0;
}

.invoice-actions {
  display: flex;
  gap: 0.75rem;
  padding: 1.25rem 2rem;
  background: #ffffff;
  border-top: 1px solid #f1f5f9;
}
.invoice-btn {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.75rem 1rem;
  border-radius: 0.75rem;
  font-size: 0.875rem;
  font-weight: 700;
  cursor: pointer;
  transition: all 0.2s;
}
.invoice-btn--outline {
  background: #ffffff;
  color: #334155;
  border: 1.5px solid #cbd5e1;
}
.invoice-btn--outline:hover {
  background: #f8fafc;
  border-color: #94a3b8;
}
.invoice-btn--primary {
  background: linear-gradient(135deg, #f97316, #ea580c);
  color: #ffffff;
  border: none;
  box-shadow: 0 4px 12px rgba(249, 115, 22, 0.25);
}
.invoice-btn--primary:hover {
  box-shadow: 0 6px 16px rgba(249, 115, 22, 0.35);
  transform: translateY(-1px);
}
</style>
